// /src/services/facebook/constants.js


export const FACEBOOK_ACCOUNTS_SHEET_NAME = "[FB] BM & Ad Accounts"; // Kept for billing logic, though should be replaced by DB call

export const BATCH_SERVER_URL = process.env.BATCH_SERVER_URL || "http://14.225.253.94:8010";
export const FACEBOOK_API_VERSION = "v24.0";

// --- Data Transformation Maps ---

export const CONVERSION_METRICS_MAP = {
  // --- Messaging ---
  "New Messaging Connections": {
    api_field: "actions:onsite_conversion.messaging_conversation_started_7d",
    parent_field: "actions",
  },
  "Cost per New Messaging": {
    api_field:
      "cost_per_action_type:onsite_conversion.messaging_conversation_started_7d",
    parent_field: "cost_per_action_type",
  },
  // --- Leads ---
  Leads: {
    api_field: "actions:lead",
    parent_field: "actions",
  },
  "Cost Leads": {
    api_field: "cost_per_action_type:lead",
    parent_field: "cost_per_action_type",
  },
  // --- Purchases (Tổng hợp và chi tiết) ---
  Purchases: {
    api_field: "actions:omni_purchase",
    parent_field: "actions",
  },
  "Cost Purchases": {
    api_field: "cost_per_action_type:omni_purchase",
    parent_field: "cost_per_action_type",
  },
  "Purchase Value": {
    api_field: "action_values:omni_purchase",
    parent_field: "action_values",
  },
  "Purchase ROAS": {
    api_field: "purchase_roas",
    parent_field: "purchase_roas",
  },
  "Website Purchases": {
    api_field: "actions:offsite_conversion.fb_pixel_purchase",
    parent_field: "actions",
  },
  "On-Facebook Purchases": {
    api_field: "actions:onsite_conversion.purchase",
    parent_field: "actions",
  },
};

export const EFFECTIVE_STATUS_FILTERS = {
  adset: ["ACTIVE", "PAUSED", "CAMPAIGN_PAUSED", "ARCHIVED"],
  ad: [
    "ACTIVE",
    "PAUSED",
    "ADSET_PAUSED",
    "CAMPAIGN_PAUSED",
    "WITH_ISSUES",
    "PENDING_REVIEW",
    "DISAPPROVED",
    "PREAPPROVED",
    "IN_PROCESS",
    "PENDING_BILLING_INFO",
    "ARCHIVED",
  ],
};

export const CURRENCY_OFFSETS = {
  DZD: 100,
  ARS: 100,
  AUD: 100,
  BHD: 100,
  BDT: 100,
  BOB: 100,
  BGN: 100,
  BRL: 100,
  GBP: 100,
  CAD: 100,
  CLP: 1,
  CNY: 100,
  COP: 1,
  CRC: 1,
  HRK: 100,
  CZK: 100,
  DKK: 100,
  EGP: 100,
  EUR: 100,
  GTQ: 100,
  HNL: 100,
  HKD: 100,
  HUF: 1,
  ISK: 1,
  INR: 100,
  IDR: 1,
  ILS: 100,
  JPY: 1,
  JOD: 100,
  KES: 100,
  KRW: 1,
  LVL: 100,
  LTL: 100,
  MOP: 100,
  MYR: 100,
  MXN: 100,
  NZD: 100,
  NIO: 100,
  NGN: 100,
  NOK: 100,
  PKR: 100,
  PYG: 1,
  PEN: 100,
  PHP: 100,
  PLN: 100,
  QAR: 100,
  RON: 100,
  RUB: 100,
  SAR: 100,
  RSD: 100,
  SGD: 100,
  SKK: 100,
  ZAR: 100,
  SEK: 100,
  CHF: 100,
  TWD: 1,
  THB: 100,
  TRY: 100,
  AED: 100,
  UAH: 100,
  USD: 100,
  UYU: 100,
  VEF: 100,
  VND: 1,
  FBZ: 100,
  VES: 100,
};

export const FUNDING_SOURCE_TYPE_MAP = {
  1: "CREDIT_CARD",
  12: "PAYPAL_TOKEN",
  13: "PAYPAL_BILLING_AGREEMENT",
  17: "DIRECT_DEBIT",
  20: "STORED_BALANCE",
};

// --- Main Template Structure ---

export const FACEBOOK_REPORT_TEMPLATES_STRUCTURE = [
  {
    groupName: "(FAD) Facebook Ads Data",
    templates: [
      {
        name: "Campaign Overview Report",
        config: {
          type: "FAD_PERFORMANCE",
          api_params: { level: "campaign" },
          selectable_fields: {
            "1.Thông tin định danh": [
              "id",
              "name",
              "objective",
              "account_id",
              "account_name",
            ],
            "2.Trạng thái & Thời gian": [
              "status",
              "effective_status",
              "start_time",
              "stop_time",
              "created_time",
              "updated_time",
            ],
            "3.Cấu hình Đấu thầu": ["buying_type", "bid_strategy"],
            "4.Chỉ số Hiệu suất": [
              "spend",
              "reach",
              "clicks",
              "cpc",
              "cpm",
              "ctr",
            ],
            "5.Khoảng thời gian tải dữ liệu": ["date_start", "date_stop"],
            "6.Chỉ số Hiệu suất & Chuyển đổi": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
          },
          campaign_fields: [
            "id",
            "name",
            "objective",
            "account_id",
            "status",
            "effective_status",
            "start_time",
            "stop_time",
            "created_time",
            "updated_time",
            "buying_type",
            "bid_strategy",
          ],
          insight_fields: [
            "spend",
            "reach",
            "clicks",
            "cpc",
            "cpm",
            "ctr",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Campaign Performance by Age",
        config: {
          type: "FAD_CAMPAIGN_BY_AGE",
          api_params: {
            level: "campaign",
            breakdowns: "age",
          },
          selectable_fields: {
            "1.Thông tin Chiến dịch": [
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
            ],
            "2.Phân loại (Breakdown)": ["age"],
            "3.Chỉ số Hiệu suất & Chuyển đổi": [
              "spend",
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
            "4.Khoảng thời gian tải dữ liệu": ["date_start", "date_stop"],
          },
          campaign_fields: ["id", "name"],
          insight_fields: [
            "spend",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Campaign Performance by Gender",
        config: {
          type: "FAD_CAMPAIGN_BY_GENDER", // Type updated from original
          api_params: {
            level: "campaign",
            breakdowns: "gender",
          },
          selectable_fields: {
            "1.Thông tin Chiến dịch": [
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
            ],
            "2.Phân loại (Breakdown)": ["gender"],
            "3.Chỉ số Hiệu suất & Chuyển đổi": [
              "spend",
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
            "4.Khoảng thời gian tải dữ liệu": ["date_start", "date_stop"],
          },
          campaign_fields: ["id", "name"],
          insight_fields: [
            "spend",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Campaign Performance by Platform",
        config: {
          type: "FAD_CAMPAIGN_PLATFORM",
          api_params: {
            level: "campaign",
            breakdowns: ["publisher_platform", "platform_position"],
          },
          selectable_fields: {
            "1.Thông tin Định danh": [
              "account_id",
              "account_name",
              "campaign_id",
              "campaign_name",
            ],
            "2.Phân loại (Breakdown)": [
              "publisher_platform",
              "platform_position",
            ],
            "3.Thời gian": ["date_start", "date_stop"],
            "4.Chỉ số Hiệu suất": ["spend", "impressions", "clicks"],
            "5.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
          },
          insight_fields: [
            "account_id",
            "account_name",
            "campaign_id",
            "campaign_name",
            "spend",
            "impressions",
            "clicks",
            "date_start",
            "date_stop",
            "actions",
            "action_values",
          ],
        },
      },
      {
        name: "Campaign Performance by Region",
        config: {
          type: "FAD_CAMPAIGN_BY_REGION",
          api_params: {
            level: "campaign",
            breakdowns: "region",
          },
          selectable_fields: {
            "1.Thông tin Chiến dịch": [
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
            ],
            "2.Phân loại (Breakdown)": ["region"],
            "3.Chỉ số Hiệu suất": ["spend", "impressions", "clicks", "ctr"],
            "4.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
            "5.Khoảng thời gian lấy dữ liệu": ["date_start", "date_stop"],
          },
          insight_fields: [
            "spend",
            "impressions",
            "clicks",
            "ctr",
            "actions",
            "action_values",
            "cost_per_action_type",
          ],
        },
      },
      {
        name: "Ad Set Performance Report",
        config: {
          type: "FAD_PERFORMANCE_ADSET",
          api_params: { level: "adset" },
          selectable_fields: {
            "1.Thông tin định danh": [
              "id",
              "name",
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
            ],
            "2.Trạng thái & Chẩn đoán": [
              "status",
              "effective_status",
              "created_time",
            ],
            "3.Ngân sách": [
              "daily_budget",
              "lifetime_budget",
              "budget_remaining",
            ],
            "4.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "reach",
              "clicks",
              "ctr",
              "cpc",
              "cpm",
            ],
            "5.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
            "Khoảng thời gian lấy dữ liệu": ["date_start", "date_stop"],
          },
          adset_fields: [
            "id",
            "name",
            "campaign{name,id}",
            "status",
            "effective_status",
            "learning_stage_info",
            "issues_info",
            "daily_budget",
            "lifetime_budget",
            "budget_remaining",
            "created_time",
          ],
          insight_fields: [
            "spend",
            "impressions",
            "reach",
            "clicks",
            "ctr",
            "cpc",
            "cpm",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Ad Performance Report",
        config: {
          type: "FAD_PERFORMANCE_AD",
          api_params: { level: "ad" },
          selectable_fields: {
            "1.Thông tin định danh": [
              "id",
              "name",
              "adset_id",
              "adset_name",
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
              "created_time",
              "updated_time",
            ],
            "3.Trạng thái & Chẩn đoán": ["status", "effective_status"],
            "4.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "reach",
              "clicks",
              "ctr",
              "cpc",
              "cpm",
              "frequency",
            ],
            "5.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
            "6.Khoảng thời gian lấy dữ liệu": ["date_start", "date_stop"],
          },
          ad_fields: [
            "id",
            "name",
            "adset{name,id}",
            "campaign{name,id}",
            "status",
            "effective_status",
            "issues_info",
            "ad_review_feedback",
            "creative{instagram_permalink_url}",
            "created_time",
            "updated_time",
          ],
          insight_fields: [
            "spend",
            "impressions",
            "reach",
            "clicks",
            "ctr",
            "cpc",
            "cpm",
            "frequency",
            "actions",
            "cost_per_action_type",
            "action_values",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Account Daily Report",
        config: {
          type: "FAD_ACCOUNT_DAILY",
          api_params: {
            level: "account",
            time_increment: 1,
            action_report_time: "conversion",
          },
          selectable_fields: {
            "1.Thông tin định danh": [
              "account_id",
              "account_name",
              "account_currency",
              "date_start",
              "date_stop",
            ],
            "2.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "clicks",
              "cpc",
              "cpm",
              "ctr",
              "reach",
              "frequency",
            ],
            "3.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
          },
          account_fields: ["id", "name", "account_currency"],
          insight_fields: [
            "spend",
            "impressions",
            "clicks",
            "cpc",
            "cpm",
            "ctr",
            "reach",
            "frequency",
            "date_start",
            "date_stop",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Campaign Daily Report",
        config: {
          type: "FAD_CAMPAIGN_DAILY",
          api_params: {
            level: "campaign",
            time_increment: 1,
            action_report_time: "conversion",
          },
          selectable_fields: {
            "1.Thông tin định danh": [
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
              "date_start",
              "date_stop",
            ],
            "2.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "reach",
              "clicks",
              "cpc",
              "cpm",
              "ctr",
              "frequency",
            ],
            "3.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
          },
          insight_fields: [
            "campaign_id",
            "campaign_name",
            "account_id",
            "account_name",
            "spend",
            "impressions",
            "reach",
            "clicks",
            "cpc",
            "cpm",
            "ctr",
            "frequency",
            "date_start",
            "date_stop",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Ad Set Daily Report",
        config: {
          type: "FAD_ADSET_DAILY",
          api_params: {
            level: "adset",
            time_increment: 1,
            action_report_time: "conversion",
          },
          selectable_fields: {
            "Thông tin định danh": [
              "id",
              "name",
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
              "date_start",
              "date_stop",
            ],
            "2.Trạng thái & Chẩn đoán": ["status", "effective_status"],
            "3.Ngân sách": [
              "daily_budget",
              "lifetime_budget",
              "budget_remaining",
            ],
            "4.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "reach",
              "clicks",
              "ctr",
              "cpc",
              "cpm",
              "frequency",
            ],
            "5.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
            ],
         },
          adset_fields: [
            "id",
            "name",
            "campaign{name,id}",
            "status",
            "effective_status",
            "daily_budget",
            "lifetime_budget",
            "budget_remaining",
          ],
          insight_fields: [
            "spend",
            "impressions",
            "reach",
            "clicks",
            "ctr",
            "cpc",
            "cpm",
            "frequency",
            "date_start",
            "date_stop",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Ad Daily Report",
        config: {
          type: "FAD_AD_DAILY",
          api_params: {
            level: "ad",
            time_increment: 1,
            action_report_time: "conversion",
          },
          selectable_fields: {
            "1.Thông tin định danh": [
              "id",
              "name",
              "adset_id",
              "adset_name",
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
              "date_start",
              "date_stop",
            ],
            "2.Trạng thái & Thời gian": [
              "status",
              "effective_status",
              "created_time",
            ],
            "3.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "reach",
              "clicks",
              "ctr",
              "cpc",
              "cpm",
              "frequency",
            ],
            "4.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Leads",
              "Cost Leads",
              "Purchases",
              "Cost Purchases",
              "Purchase Value",
              "Purchase ROAS",
              "Website Purchases",
              "On-Facebook Purchases",
           ],
          },
          ad_fields: [
            "id",
            "name",
            "adset{name,id}",
            "campaign{name,id}",
            "status",
            "effective_status",
            "created_time",
          ],
          insight_fields: [
            "spend",
            "impressions",
            "reach",
            "clicks",
            "ctr",
            "cpc",
            "cpm",
            "frequency",
            "date_start",
            "date_stop",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "Ad Creative Report",
        config: {
          type: "FAD_AD_CREATIVE",
          api_params: { level: "ad" },
          selectable_fields: {
            "1.Thông tin định danh": [
              "id",
              "name",
              "adset_id",
              "adset_name",
              "campaign_id",
              "campaign_name",
              "account_id",
              "account_name",
            ],
            "2.Trạng thái": ["status", "effective_status"],
            "3.Thông tin Sáng tạo": [
              "creative_id",
              "actor_id",
              "page_name",
              "creative_title",
              "creative_body",
              "creative_thumbnail_url",
              "creative_thumbnail_raw_url",
              "creative_link",
            ],
            "4.Chỉ số Hiệu suất": [
              "spend",
              "impressions",
              "Leads",
              "Cost Leads",
              "reach",
              "clicks",
              "ctr",
              "cpc",
              "cpm",
            ],
            "5.Chỉ số Chuyển đổi (Conversion)": [
              "New Messaging Connections",
              "Cost per New Messaging",
              "Purchases",
              "Purchase Value",
              "Purchase ROAS",
            ],
            "6.Khoảng thời gian lấy dữ liệu": ["date_start", "date_stop"],
          },
          ad_fields: [
            "id",
            "name",
            "status",
            "effective_status",
            "adset{id,name}",
            "campaign{id,name}",
            "creative{id,name,object_story_id,title,body,thumbnail_url,actor_id}",
          ],
          insight_fields: [
            "spend",
            "impressions",
            "Leads",
            "Cost Leads",
            "reach",
            "clicks",
            "ctr",
            "cpc",
            "cpm",
            "actions",
            "action_values",
            "cost_per_action_type",
            "purchase_roas",
          ],
        },
      },
      {
        name: "BM & Ad Accounts",
        config: {
          type: "FAD_BM_ACCOUNTS",
          selectable_fields: {
            "1.Thông tin Business Manager": [
              "bm_id",
              "bm_name",
              "bm_created_time",
              "bm_verification_status",
              "bm_profile_picture_uri",
            ],
            "2.Thông tin Tài khoản QC": [
              "account_type",
              "account_id",
              "account_name",
              "account_status_text",
              "currency",
              "timezone_name",
              "amount_spent",
              "balance",
              "current_payment_method",
              "tax_and_fee",
            ],
          },
        },
      },
    ],
  },
  {
    groupName: "(FBT) FB Billing Tool",
    templates: [{ name: "FB Billing Data", config: { type: "FBT_BILLING" } }],
  },
  {
    groupName: "(MPI) Meta Page Insight",
    templates: [
      // ... (MPI templates are omitted as requested)
    ],
  },
];
