-- CreateTable
CREATE TABLE "POS_BasicReport" (
    "pkId" TEXT NOT NULL DEFAULT gen_random_uuid(),
    "user_id" TEXT NOT NULL,
    "task_id" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "is_primary_row" BOOLEAN,
    "order_id" TEXT,
    "display_id" TEXT,
    "system_id" TEXT,
    "shop_id" TEXT,
    "conversation_id" TEXT,
    "order_link" TEXT,
    "tracking_link" TEXT,
    "created_at" TIMESTAMP(3),
    "created_date" TEXT,
    "updated_at" TIMESTAMP(3),
    "status_code" INTEGER,
    "status_name" TEXT,
    "sub_status" TEXT,
    "is_locked" BOOLEAN,
    "is_received_at_shop" BOOLEAN,
    "source_name" TEXT,
    "source_id" TEXT,
    "ads_source" TEXT,
    "ad_id" TEXT,
    "page_id" TEXT,
    "page_name" TEXT,
    "page_username" TEXT,
    "post_id" TEXT,
    "marketer_id" TEXT,
    "utm_source" TEXT,
    "utm_medium" TEXT,
    "utm_campaign" TEXT,
    "utm_content" TEXT,
    "utm_term" TEXT,
    "creator_id" TEXT,
    "creator_name" TEXT,
    "seller_name" TEXT,
    "seller_id" TEXT,
    "seller_assigned_at" TIMESTAMP(3),
    "care_staff_name" TEXT,
    "care_staff_id" TEXT,
    "care_assigned_at" TIMESTAMP(3),
    "last_editor_name" TEXT,
    "customer_system_id" TEXT,
    "customer_uuid" TEXT,
    "customer_name" TEXT,
    "customer_phone" TEXT,
    "customer_email" TEXT,
    "customer_gender" TEXT,
    "full_address" TEXT,
    "street_address" TEXT,
    "ward_name" TEXT,
    "district_name" TEXT,
    "province_name" TEXT,
    "postal_code" TEXT,
    "currency" TEXT,
    "total_amount" DOUBLE PRECISION,
    "total_after_sub_discount" DOUBLE PRECISION,
    "total_discount" DOUBLE PRECISION,
    "amount_to_collect" DOUBLE PRECISION,
    "cod_amount" DOUBLE PRECISION,
    "carrier_cod_amount" DOUBLE PRECISION,
    "tax_amount" DOUBLE PRECISION,
    "surcharge_amount" DOUBLE PRECISION,
    "surcharge_cost" DOUBLE PRECISION,
    "shipping_fee_customer" DOUBLE PRECISION,
    "shipping_fee_carrier" DOUBLE PRECISION,
    "marketplace_fee" DOUBLE PRECISION,
    "is_customer_paying_shipping" BOOLEAN,
    "is_free_shipping" BOOLEAN,
    "payment_methods" TEXT,
    "payment_cash" DOUBLE PRECISION,
    "payment_transfer" DOUBLE PRECISION,
    "payment_card" DOUBLE PRECISION,
    "payment_momo" DOUBLE PRECISION,
    "payment_vnpay" DOUBLE PRECISION,
    "payment_qrpay" DOUBLE PRECISION,
    "payment_kredivo" DOUBLE PRECISION,
    "payment_fundiin" DOUBLE PRECISION,
    "payment_prepaid" DOUBLE PRECISION,
    "payment_points" DOUBLE PRECISION,
    "exchange_value" DOUBLE PRECISION,
    "carrier_name" TEXT,
    "tracking_code" TEXT,
    "sent_to_carrier_at" TIMESTAMP(3),
    "shipping_service" TEXT,
    "warehouse_id" TEXT,
    "warehouse_name" TEXT,
    "warehouse_address" TEXT,
    "order_total_quantity" INTEGER,
    "order_item_count" INTEGER,
    "item_id" TEXT,
    "product_code" TEXT,
    "sku_code" TEXT,
    "product_name" TEXT,
    "item_quantity" DOUBLE PRECISION,
    "item_retail_price" DOUBLE PRECISION,
    "item_cost_price" DOUBLE PRECISION,
    "item_discount" DOUBLE PRECISION,
    "item_price_final" DOUBLE PRECISION,
    "item_total_amount" DOUBLE PRECISION,
    "item_weight" DOUBLE PRECISION,
    "item_note" TEXT,
    "is_bonus_item" BOOLEAN,
    "is_wholesale_item" BOOLEAN,
    "internal_note" TEXT,
    "printed_note" TEXT,
    "tags" TEXT,
    "is_livestream" BOOLEAN,
    "is_live_shopping" BOOLEAN,
    "is_social_commerce" BOOLEAN,
    "is_exchange_order" BOOLEAN,
    "return_reason_id" TEXT,
    "return_reason_name" TEXT,

    CONSTRAINT "POS_BasicReport_pkey" PRIMARY KEY ("pkId")
);

-- CreateIndex
CREATE INDEX "POS_BasicReport_user_id_idx" ON "POS_BasicReport"("user_id");

-- CreateIndex
CREATE INDEX "POS_BasicReport_user_id_created_at_idx" ON "POS_BasicReport"("user_id", "created_at");
